config/routes.rb
Rails.application.routes.draw do
  # HOMEPAGE
  root "welcome#index"


  # FOR LOGIN/LOGOUT
  get "/registration", to: "sessions#new", as: "registration" # login/signup page
  post "/login", to: "sessions#create", as: "login"           # creates session -> homepage
  delete "/logout", to: "sessions#destroy", as: "logout"      # deletes session -> login/signup page
  get "users/verify", to: 'users#show_verify', as: "verify"   # verification code form page
  post "users/verify"                                       # creates user -> homepage
  post "users/resend"                                         # resends code -> verification code form page

  # For new Users
  resources :users, only: [:create]

  # Searching a moment
  post "moments/search", to: "moments#search", as: "search"

  # API
  post "/sms/received_message", to: "api#received_message"
end

app/views/layouts/_flash_messages.html.erb
<% if flash[:messages] %>
  <% flash[:messages].each do |key, value| %>
    <h5 class="alert alert-success">
      <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
      <%= key.to_s.titlecase %>: <%= value %>
    </h5>
  <% end %>
<% end %>

<% if flash[:errors] %>
  <% flash[:errors].each do |key, value| %>
    <h5 class="alert alert-warning">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <%= key.to_s.titlecase %>: <%= value %>
    </h5>
  <% end %>
<% end %>

<% if flash[:notices] %>
  <% flash[:notices].each do |key, value| %>
    <h5 class="alert alert-warning">
      <span aria-hidden="true"></span>
      <%= key.to_s.titlecase %>: <%= value %>
    </h5>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<% if session[:id] && @user %>
  <nav class="navbar navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Stash This Moment", root_path, class: "navbar-brand title-font" %>

        <div class="navbar-collapse collapse">
          <%= form_tag(search_path, method: "post", class: "navbar-form center-search") do %>
            <div class="form-group">
              <%= label_tag(:search_term, "Search for:", class: "hidden") %>
              <%= text_field_tag(:search_term, nil, class: "form-control", placeholder: "Search") %>
            </div>
          <% end %>
        </div>

        <button type="button" class="navbar-toggle navbar-btn" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div id="navbar" class="navbar-collapse collapse" aria-expanded="true">
        <ul class="nav navbar-nav navbar-right">
          <li><p class="navbar-text stm_phone_number">(504) 315-7972</p></li>
          <li><p class="navbar-text"><%= @user.username %></p></li>
          <li><p class="navbar-text"><%= link_to "Logout", logout_path, method: :delete %></p></li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stash This Moment</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,100' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Rajdhani|Megrim' rel='stylesheet' type='text/css'>
  <link href="https://www.authy.com/form.authy.min.css" media="screen" rel="stylesheet" type="text/css">
  <script src="https://www.authy.com/form.authy.min.js" type="text/javascript"></script>
</head>
<body class=<%= background_photo_class(session[:id], @homepage, @moments, @user) %>>
  <%= render partial: "layouts/navbar" %>

  <div class="container-fluid">
    <div class=<%= flash_message_margin(session[:id], @homepage) %>>
      <%= render partial: "layouts/flash_messages" %>
    </div>

    <%= yield %>

    <footer>
      <small><%= "background image © Anthony Quintano" if background_photo_class(session[:id], @homepage, @moments, @user) == "not-logged-in" && @homepage == nil %></small>
    </footer>
  </div>
</body>
</html>